pipeline {
    agent any

    environment {
        IMAGE_NAME = "running_image"
        CONTAINER_NAME = "running_container"
    }

    stages{

        stage('check_out'){
            steps{
                git branch: 'main',
                    url: 'https://github.com/BALASUBRAMANI619/RUNNING-PLAN-APP.git'
            }
        }

        stage('build_image'){
            steps{
                sh '''
                    docker build -t $IMAGE_NAME .
                '''
            }
        }

        stage('remove_old_container'){
            steps{
                sh ''' docker rm -f $CONTAINER_NAME || true
                '''
            }
        }

        stage('run_container'){
            steps{
                sh ''' docker run -d -p 5000:5000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }
    }
    post {
        success{
            echo " ✅ Deployment successful"
        }
        failure{
            echo "❌ Deployment failed"
        }
    }
}