pipeline {
    agent any

    environment {
        Image_name = running_image
        Container_name = running_container
    }

    Stages{

        stage('check_out'){
            steps{
                git branch: 'main',
                    url: 'https://github.com/BALASUBRAMANI619/RUNNING-PLAN-APP.git'
            }
        }

        stage('build_image'){
            steps{
                sh '''
                    docker build -t $Image_name .
                '''
            }
        }

        stage('remove_old_container'){
            steps{
                sh ''' docker rm -f $Container_name || true
                '''
            }
        }

        stage('run_container'){
            steps{
                sh ''' docker run -d -p 5000:5000 --name $Container_name $Image_name
                '''
            }
        }
    }
    post {
        success{
            echo "✅ Deployment successful"
        }
        failure{
            echo "❌ Deployment failed"
        }
    }
}